/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mario
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        AgregarAuto = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        MostrarAuto = new javax.swing.JButton();
        EliminarAuto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sitka Heading", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Need For Speed");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 340, 60));

        AgregarAuto.setForeground(new java.awt.Color(0, 0, 0));
        AgregarAuto.setText("Agregar Auto");
        AgregarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarAutoActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 140, 40));

        modificar.setForeground(new java.awt.Color(0, 0, 0));
        modificar.setText("Modificar ");
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 140, 40));

        MostrarAuto.setForeground(new java.awt.Color(0, 0, 0));
        MostrarAuto.setText("Mostrar Autos");
        getContentPane().add(MostrarAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 140, 40));

        EliminarAuto.setForeground(new java.awt.Color(0, 0, 0));
        EliminarAuto.setText("Eliminar Auto");
        getContentPane().add(EliminarAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 140, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarAutoActionPerformed
        agregarA vnt3 = new agregarA();
        vnt3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AgregarAutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarAuto;
    private javax.swing.JButton EliminarAuto;
    private javax.swing.JButton MostrarAuto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton modificar;
    // End of variables declaration//GEN-END:variables
}
